parameters:
    env(DATABASE_URL): 'postgresql://postgres:password@trading-app-db:5432/trading_app?serverVersion=15&charset=utf8'

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            postgres_timestamp: App\Repository\Doctrine\Type\PostgresTimestampType
            uuid: Ramsey\Uuid\Doctrine\UuidType
        mapping_types:
            timeframe: string
            signal_side: string
            guid: uuid

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Trading:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Trading/Entity'
                prefix: 'App\Trading\Entity'
                alias: Trading
            MtfValidator:
                is_bundle: false
                dir: '%kernel.project_dir%/src/MtfValidator/Entity'
                prefix: 'App\MtfValidator\Entity'
                alias: MtfValidator
            Provider:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Provider/Entity'
                prefix: 'App\Provider\Entity'
                alias: Provider
