# routes

controllers:
  resource: '../src/Controller/'
  type: attribute

# Import MTF routes
mtf_api:
    resource: routes_mtf.yaml

# WebSocket routes (moved to WebSocketDispatcherController)

# WebSocket Dispatcher routes
ws_dispatch:
  path: /ws/dispatch
  controller: App\Controller\Web\WebSocketDispatcherController::dispatch
  methods: [POST]

ws_rebalance:
  path: /ws/rebalance
  controller: App\Controller\Web\WebSocketDispatcherController::rebalance
  methods: [POST]

ws_assignments:
  path: /ws/assignments
  controller: App\Controller\Web\WebSocketDispatcherController::getAssignments
  methods: [GET]

# Explicit web controllers to ensure route discovery
mtf_web_audit:
  resource: '../src/MtfValidator/Controller/Web/MtfAuditController.php'
  type: attribute

mtf_web_stats:
  resource: '../src/MtfValidator/Controller/Web/MtfStatsController.php'
  type: attribute

mtf_web_states:
  resource: '../src/MtfValidator/Controller/Web/MtfStateController.php'
  type: attribute

mtf_web_switches:
  resource: '../src/MtfValidator/Controller/Web/MtfSwitchWebController.php'
  type: attribute

mtf_web_locks:
  resource: '../src/MtfValidator/Controller/Web/MtfLockWebController.php'
  type: attribute

# MTF API controllers
mtf_api_audit:
  resource: '../src/MtfValidator/Controller/Api/MtfAuditController.php'
  type: attribute

# Indicator controllers
indicator_web:
  resource: '../src/Indicator/Controller/IndicatorTestController.php'
  type: attribute

indicator_api:
  resource: '../src/Indicator/Controller/IndicatorApiController.php'
  type: attribute

# TradeEntry controllers
trade_entry_web:
  resource: '../src/TradeEntry/Controller/'
  type: attribute
